version = "1.1.15"

[class]
"[?i]*floorp" = "󰖟"
"[?i]*zen-alpha" = "󰖟"
"org.gnome.Calculator" = ""
DEFAULT = "󰖯"
"[Ff]irefox" = "󰈹"
"(?i)Codium" = "󰨞"
"(?i)Joplin" = ""
"(?i)jetbrains-idea" = ""
pavucontrol = ""
"(?i)Steam" = "󰓓"
Brave-browser = ""
"(?i)Thunderbird" = ""
"(?i)kitty" = "󰄛"
"(?i)jetbrains-studio" = "󰀴"
"(?i)Thunar" = ""
"(?i)wezterm" = ""
"(?i)scratchpad" = "󱞂"
"(?i)inkscape" = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
9 = "󰎼"
4 = "󰎭"
10 = "󰽽"
0 = "󰎡"
3 = "󰎪"
2 = "󰎧"
5 = "󰎱"
6 = "󰎳"
1 = "󰎤"
7 = "󰎶"
8 = "󰎹"

[title_in_class."FFPWA.*"]
"Ollama Open WebUI" = " "
"Discord" = "󰙯 "

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class."^$"]
"(?i)spotify" = ""
"(?i)wezterm" = ""
"(?i)kitty" = "󰄛"

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"[Ss]team" = "^(Friends List.*)?$"
"(?i)fcitx" = ".*"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = " <span color='#9ccfd8' font_size='x-large' rise='-2300'>{name}</span><span font-size='x-large' color='#e0def4' rise='-1300'>{clients}</span>"
workspace_empty = "<span color='#6e6a86' font-size='x-large' rise='-2300'>{name}</span>"
client = "{icon}"
client_fullscreen = "[<span font_size='7pt' >{icon}</span>]"
client_active = "<span color='#d7827e'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
