version = "1.1.14"

[class]
DEFAULT = "󰖯"
"(?i)jetbrains-studio" = "󰀴"
"[Ff]irefox" = "󰈹"
"[?i]*floorp" = "󰾔"
"(?i)Steam" = "󰓓"
"(?i)Thunar" = ""
Brave-browser = ""
"(?i)Joplin" = ""
"(?i)Thunderbird" = ""
"(?i)jetbrains-idea" = ""
"(?i)Kitty" = ""
"(?i)Wezterm" = ""
"(?i)Codium" = "󰨞"
pavucontrol = ""
"org.gnome.Calculator" = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
0 = "󰎡"
1 = "󰎤"
2 = "󰎧"
3 = "󰎪"
4 = "󰎭"
5 = "󰎱"
6 = "󰎳"
7 = "󰎶"
8 = "󰎹"
9 = "󰎼"
10 = "󰽽"

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class."^$"]
"(?i)spotify" = ""

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
aProgram = "^$"
"[Ss]team" = "^(Friends List.*)?$"
"(?i)TestApp" = ""
"" = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = " <span color='#9ccfd8' font_size='x-large' rise='-2300'>{name}</span><span font-size='x-large' color='#e0def4' rise='-1300'>{clients}</span>"
workspace_empty = "<span color='#6e6a86' font-size='x-large' rise='-2300'>{name}</span>"
client = "{icon}"
client_fullscreen = "[<span font_size='7pt' >{icon}</span>]"
client_active = "<span color='#d7827e'>{icon}</span>"
